name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ['1.19.13', '1.20.10', '1.21.3']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Test
        run: go test -v ./...
